// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fumkob/ezqrin-server/internal/usecase/participant (interfaces: Usecase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_usecase.go -package=mocks . Usecase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/fumkob/ezqrin-server/internal/domain/entity"
	participant "github.com/fumkob/ezqrin-server/internal/usecase/participant"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockUsecase) BulkCreate(ctx context.Context, userID uuid.UUID, isAdmin bool, input participant.BulkCreateInput) (participant.BulkCreateOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", ctx, userID, isAdmin, input)
	ret0, _ := ret[0].(participant.BulkCreateOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockUsecaseMockRecorder) BulkCreate(ctx, userID, isAdmin, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockUsecase)(nil).BulkCreate), ctx, userID, isAdmin, input)
}

// Create mocks base method.
func (m *MockUsecase) Create(ctx context.Context, userID uuid.UUID, isAdmin bool, input participant.CreateParticipantInput) (*entity.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, isAdmin, input)
	ret0, _ := ret[0].(*entity.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUsecaseMockRecorder) Create(ctx, userID, isAdmin, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUsecase)(nil).Create), ctx, userID, isAdmin, input)
}

// Delete mocks base method.
func (m *MockUsecase) Delete(ctx context.Context, userID uuid.UUID, isAdmin bool, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, isAdmin, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUsecaseMockRecorder) Delete(ctx, userID, isAdmin, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUsecase)(nil).Delete), ctx, userID, isAdmin, id)
}

// ExportCSV mocks base method.
func (m *MockUsecase) ExportCSV(ctx context.Context, userID uuid.UUID, isAdmin bool, eventID uuid.UUID) ([]*entity.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportCSV", ctx, userID, isAdmin, eventID)
	ret0, _ := ret[0].([]*entity.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportCSV indicates an expected call of ExportCSV.
func (mr *MockUsecaseMockRecorder) ExportCSV(ctx, userID, isAdmin, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportCSV", reflect.TypeOf((*MockUsecase)(nil).ExportCSV), ctx, userID, isAdmin, eventID)
}

// GetByID mocks base method.
func (m *MockUsecase) GetByID(ctx context.Context, userID uuid.UUID, isAdmin bool, id uuid.UUID) (*entity.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userID, isAdmin, id)
	ret0, _ := ret[0].(*entity.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUsecaseMockRecorder) GetByID(ctx, userID, isAdmin, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUsecase)(nil).GetByID), ctx, userID, isAdmin, id)
}

// GetQRCode mocks base method.
func (m *MockUsecase) GetQRCode(ctx context.Context, userID uuid.UUID, isAdmin bool, id uuid.UUID, format string, size int) (participant.QRCodeOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQRCode", ctx, userID, isAdmin, id, format, size)
	ret0, _ := ret[0].(participant.QRCodeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQRCode indicates an expected call of GetQRCode.
func (mr *MockUsecaseMockRecorder) GetQRCode(ctx, userID, isAdmin, id, format, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQRCode", reflect.TypeOf((*MockUsecase)(nil).GetQRCode), ctx, userID, isAdmin, id, format, size)
}

// List mocks base method.
func (m *MockUsecase) List(ctx context.Context, userID uuid.UUID, isAdmin bool, input participant.ListParticipantsInput) (participant.ListParticipantsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, isAdmin, input)
	ret0, _ := ret[0].(participant.ListParticipantsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUsecaseMockRecorder) List(ctx, userID, isAdmin, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUsecase)(nil).List), ctx, userID, isAdmin, input)
}

// SendQRCodes mocks base method.
func (m *MockUsecase) SendQRCodes(ctx context.Context, userID uuid.UUID, isAdmin bool, input participant.SendQRCodesInput) (participant.SendQRCodesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendQRCodes", ctx, userID, isAdmin, input)
	ret0, _ := ret[0].(participant.SendQRCodesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendQRCodes indicates an expected call of SendQRCodes.
func (mr *MockUsecaseMockRecorder) SendQRCodes(ctx, userID, isAdmin, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendQRCodes", reflect.TypeOf((*MockUsecase)(nil).SendQRCodes), ctx, userID, isAdmin, input)
}

// Update mocks base method.
func (m *MockUsecase) Update(ctx context.Context, userID uuid.UUID, isAdmin bool, id uuid.UUID, input participant.UpdateParticipantInput) (*entity.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userID, isAdmin, id, input)
	ret0, _ := ret[0].(*entity.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUsecaseMockRecorder) Update(ctx, userID, isAdmin, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUsecase)(nil).Update), ctx, userID, isAdmin, id, input)
}
