// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fumkob/ezqrin-server/internal/domain/repository (interfaces: ParticipantRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_participant_repository.go -package=mocks . ParticipantRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/fumkob/ezqrin-server/internal/domain/entity"
	repository "github.com/fumkob/ezqrin-server/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockParticipantRepository is a mock of ParticipantRepository interface.
type MockParticipantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockParticipantRepositoryMockRecorder
	isgomock struct{}
}

// MockParticipantRepositoryMockRecorder is the mock recorder for MockParticipantRepository.
type MockParticipantRepositoryMockRecorder struct {
	mock *MockParticipantRepository
}

// NewMockParticipantRepository creates a new mock instance.
func NewMockParticipantRepository(ctrl *gomock.Controller) *MockParticipantRepository {
	mock := &MockParticipantRepository{ctrl: ctrl}
	mock.recorder = &MockParticipantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParticipantRepository) EXPECT() *MockParticipantRepositoryMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockParticipantRepository) BulkCreate(ctx context.Context, participants []*entity.Participant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", ctx, participants)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockParticipantRepositoryMockRecorder) BulkCreate(ctx, participants any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockParticipantRepository)(nil).BulkCreate), ctx, participants)
}

// Create mocks base method.
func (m *MockParticipantRepository) Create(ctx context.Context, participant *entity.Participant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, participant)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockParticipantRepositoryMockRecorder) Create(ctx, participant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockParticipantRepository)(nil).Create), ctx, participant)
}

// Delete mocks base method.
func (m *MockParticipantRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockParticipantRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockParticipantRepository)(nil).Delete), ctx, id)
}

// ExistsByEmail mocks base method.
func (m *MockParticipantRepository) ExistsByEmail(ctx context.Context, eventID uuid.UUID, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEmail", ctx, eventID, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEmail indicates an expected call of ExistsByEmail.
func (mr *MockParticipantRepositoryMockRecorder) ExistsByEmail(ctx, eventID, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEmail", reflect.TypeOf((*MockParticipantRepository)(nil).ExistsByEmail), ctx, eventID, email)
}

// FindByEmployeeID mocks base method.
func (m *MockParticipantRepository) FindByEmployeeID(ctx context.Context, eventID uuid.UUID, employeeID string) (*entity.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmployeeID", ctx, eventID, employeeID)
	ret0, _ := ret[0].(*entity.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmployeeID indicates an expected call of FindByEmployeeID.
func (mr *MockParticipantRepositoryMockRecorder) FindByEmployeeID(ctx, eventID, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmployeeID", reflect.TypeOf((*MockParticipantRepository)(nil).FindByEmployeeID), ctx, eventID, employeeID)
}

// FindByEventID mocks base method.
func (m *MockParticipantRepository) FindByEventID(ctx context.Context, eventID uuid.UUID, offset, limit int) ([]*entity.Participant, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEventID", ctx, eventID, offset, limit)
	ret0, _ := ret[0].([]*entity.Participant)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByEventID indicates an expected call of FindByEventID.
func (mr *MockParticipantRepositoryMockRecorder) FindByEventID(ctx, eventID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEventID", reflect.TypeOf((*MockParticipantRepository)(nil).FindByEventID), ctx, eventID, offset, limit)
}

// FindByID mocks base method.
func (m *MockParticipantRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockParticipantRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockParticipantRepository)(nil).FindByID), ctx, id)
}

// FindByQRCode mocks base method.
func (m *MockParticipantRepository) FindByQRCode(ctx context.Context, qrCode string) (*entity.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByQRCode", ctx, qrCode)
	ret0, _ := ret[0].(*entity.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByQRCode indicates an expected call of FindByQRCode.
func (mr *MockParticipantRepositoryMockRecorder) FindByQRCode(ctx, qrCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByQRCode", reflect.TypeOf((*MockParticipantRepository)(nil).FindByQRCode), ctx, qrCode)
}

// GetPaymentStats mocks base method.
func (m *MockParticipantRepository) GetPaymentStats(ctx context.Context, eventID uuid.UUID) (*repository.ParticipantPaymentStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentStats", ctx, eventID)
	ret0, _ := ret[0].(*repository.ParticipantPaymentStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentStats indicates an expected call of GetPaymentStats.
func (mr *MockParticipantRepositoryMockRecorder) GetPaymentStats(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentStats", reflect.TypeOf((*MockParticipantRepository)(nil).GetPaymentStats), ctx, eventID)
}

// HealthCheck mocks base method.
func (m *MockParticipantRepository) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockParticipantRepositoryMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockParticipantRepository)(nil).HealthCheck), ctx)
}

// Search mocks base method.
func (m *MockParticipantRepository) Search(ctx context.Context, eventID uuid.UUID, query string, offset, limit int) ([]*entity.Participant, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, eventID, query, offset, limit)
	ret0, _ := ret[0].([]*entity.Participant)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockParticipantRepositoryMockRecorder) Search(ctx, eventID, query, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockParticipantRepository)(nil).Search), ctx, eventID, query, offset, limit)
}

// Update mocks base method.
func (m *MockParticipantRepository) Update(ctx context.Context, participant *entity.Participant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, participant)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockParticipantRepositoryMockRecorder) Update(ctx, participant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockParticipantRepository)(nil).Update), ctx, participant)
}
