// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fumkob/ezqrin-server/internal/domain/repository (interfaces: CheckinRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_checkin_repository.go -package=mocks . CheckinRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/fumkob/ezqrin-server/internal/domain/entity"
	repository "github.com/fumkob/ezqrin-server/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCheckinRepository is a mock of CheckinRepository interface.
type MockCheckinRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCheckinRepositoryMockRecorder
	isgomock struct{}
}

// MockCheckinRepositoryMockRecorder is the mock recorder for MockCheckinRepository.
type MockCheckinRepositoryMockRecorder struct {
	mock *MockCheckinRepository
}

// NewMockCheckinRepository creates a new mock instance.
func NewMockCheckinRepository(ctrl *gomock.Controller) *MockCheckinRepository {
	mock := &MockCheckinRepository{ctrl: ctrl}
	mock.recorder = &MockCheckinRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckinRepository) EXPECT() *MockCheckinRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCheckinRepository) Create(ctx context.Context, checkin *entity.Checkin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, checkin)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCheckinRepositoryMockRecorder) Create(ctx, checkin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCheckinRepository)(nil).Create), ctx, checkin)
}

// Delete mocks base method.
func (m *MockCheckinRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCheckinRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCheckinRepository)(nil).Delete), ctx, id)
}

// ExistsByParticipant mocks base method.
func (m *MockCheckinRepository) ExistsByParticipant(ctx context.Context, eventID, participantID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByParticipant", ctx, eventID, participantID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByParticipant indicates an expected call of ExistsByParticipant.
func (mr *MockCheckinRepositoryMockRecorder) ExistsByParticipant(ctx, eventID, participantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByParticipant", reflect.TypeOf((*MockCheckinRepository)(nil).ExistsByParticipant), ctx, eventID, participantID)
}

// FindByEvent mocks base method.
func (m *MockCheckinRepository) FindByEvent(ctx context.Context, eventID uuid.UUID, limit, offset int) ([]*entity.Checkin, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEvent", ctx, eventID, limit, offset)
	ret0, _ := ret[0].([]*entity.Checkin)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByEvent indicates an expected call of FindByEvent.
func (mr *MockCheckinRepositoryMockRecorder) FindByEvent(ctx, eventID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEvent", reflect.TypeOf((*MockCheckinRepository)(nil).FindByEvent), ctx, eventID, limit, offset)
}

// FindByID mocks base method.
func (m *MockCheckinRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.Checkin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.Checkin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCheckinRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCheckinRepository)(nil).FindByID), ctx, id)
}

// FindByParticipant mocks base method.
func (m *MockCheckinRepository) FindByParticipant(ctx context.Context, participantID uuid.UUID) (*entity.Checkin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByParticipant", ctx, participantID)
	ret0, _ := ret[0].(*entity.Checkin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByParticipant indicates an expected call of FindByParticipant.
func (mr *MockCheckinRepositoryMockRecorder) FindByParticipant(ctx, participantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByParticipant", reflect.TypeOf((*MockCheckinRepository)(nil).FindByParticipant), ctx, participantID)
}

// GetEventStats mocks base method.
func (m *MockCheckinRepository) GetEventStats(ctx context.Context, eventID uuid.UUID) (*repository.CheckinStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventStats", ctx, eventID)
	ret0, _ := ret[0].(*repository.CheckinStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventStats indicates an expected call of GetEventStats.
func (mr *MockCheckinRepositoryMockRecorder) GetEventStats(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventStats", reflect.TypeOf((*MockCheckinRepository)(nil).GetEventStats), ctx, eventID)
}

// HealthCheck mocks base method.
func (m *MockCheckinRepository) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockCheckinRepositoryMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockCheckinRepository)(nil).HealthCheck), ctx)
}
