// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fumkob/ezqrin-server/internal/usecase/checkin (interfaces: Usecase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_usecase.go -package=mocks . Usecase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	checkin "github.com/fumkob/ezqrin-server/internal/usecase/checkin"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockUsecase) Cancel(ctx context.Context, userID uuid.UUID, isAdmin bool, checkinID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, userID, isAdmin, checkinID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockUsecaseMockRecorder) Cancel(ctx, userID, isAdmin, checkinID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockUsecase)(nil).Cancel), ctx, userID, isAdmin, checkinID)
}

// CheckIn mocks base method.
func (m *MockUsecase) CheckIn(ctx context.Context, userID uuid.UUID, isAdmin bool, input checkin.CheckInInput) (*checkin.CheckInOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIn", ctx, userID, isAdmin, input)
	ret0, _ := ret[0].(*checkin.CheckInOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIn indicates an expected call of CheckIn.
func (mr *MockUsecaseMockRecorder) CheckIn(ctx, userID, isAdmin, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIn", reflect.TypeOf((*MockUsecase)(nil).CheckIn), ctx, userID, isAdmin, input)
}

// GetStatus mocks base method.
func (m *MockUsecase) GetStatus(ctx context.Context, userID uuid.UUID, isAdmin bool, participantID uuid.UUID) (*checkin.CheckInStatusOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, userID, isAdmin, participantID)
	ret0, _ := ret[0].(*checkin.CheckInStatusOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockUsecaseMockRecorder) GetStatus(ctx, userID, isAdmin, participantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockUsecase)(nil).GetStatus), ctx, userID, isAdmin, participantID)
}

// List mocks base method.
func (m *MockUsecase) List(ctx context.Context, userID uuid.UUID, isAdmin bool, input checkin.ListCheckInsInput) (*checkin.ListCheckInsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, isAdmin, input)
	ret0, _ := ret[0].(*checkin.ListCheckInsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUsecaseMockRecorder) List(ctx, userID, isAdmin, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUsecase)(nil).List), ctx, userID, isAdmin, input)
}
